### ISSUE TITLE
Still being updated?

### ISSUE THREAD

**Issue by CMCDragonkai** [GaretJax/phpbrowscap#31]
Is this project still alive? Also how reliable is it in detecting search bots?

**Comment by quentin389** [comment]
It wasn't being updated. Now it will.

Bots detecting is as reliable as `get_browser()` detecting is. Right now there are a lot of new browsers/bots missing, because [browscap](http://tempdownloads.browserscap.com/) project got stalled. When it gets back on track this class should start returning good results once again.

Bots don't change as often as user browsers, so the situation is not that bad here, but if you want more reliable detection, try [UserAgentInfo](https://github.com/quentin389/UserAgentInfo) for the time being.

I'm closing this issue.
